### ISSUE TITLE
Compatibility issues on JDK 14

### ISSUE THREAD

**Issue by sheinbergon** [OpenHFT/Chronicle-Core#100]
Hi

as previously described in [here](https://github.com/OpenHFT/Chronicle-Queue/issues/652)

sun.nio.ch.FileChannelImpl.map0 implementation has changed on JDK 14, requiring an additional boolean param.

This makes CQ unusable on that version of the JDK (works fine on JDK 13).

Tested with CQ version 5.19.2

I've opened a [PR](https://github.com/OpenHFT/Chronicle-Core/pull/98)

**Comment by sheinbergon** [comment]
OK, resolved

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.19.4](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.19.4), [BOM-2.19.116](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.116)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
