### ISSUE TITLE
Improve EventHandler termination performance

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Core#101]
It is possible to create a subclass of InvalidEventHandlerException that only exists as a singleton (e.g. SingletonInvalidEventHandlerException) and that is statically created. EventHandlers that only use the InvalidEventHandlerException as a means of removing itself from the EventLoop could use the static Exception for pure removal with no underlying exception to signal. This will improve loop performance and reduce jittering.

Originally filed here https://github.com/OpenHFT/Chronicle-Threads/issues/32

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.19.4](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.19.4), [BOM-2.19.116](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.116)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
