### ISSUE TITLE
java 11 build failing

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Core#106]
see https://teamcity.chronicle.software/viewLog.html?buildId=405933&buildTypeId=OpenHFT_ChronicleCore_Java11Compatibility

**Comment by dpisklov** [comment]
Fixed

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
