### ISSUE TITLE
Improve reference count history output in ReferenceCounter

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Core#107]
Unexperienced users. might think printed history is actual exceptions.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
