### ISSUE TITLE
WeakReferenceCleaner thread lingering under certain conditions 

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Core#109]
When an application is run via `mvn exec:java` and subsequently completes, the exec plugin will check for threads that are alive. (including daemon threads). These threads are then interrupted and waited upon for some 30 seconds. If they are still alive, an error message is shown. It is only after this that shutdown hooks are executed. 

The way the cleaner `chronicle-weak-reference-cleaner` is handled, it will always be reported as alive and thus it will create the problems above. It would be better to run said thread as a plain daemon thread.

**Comment by JerryShea** [comment]
You can also use `-Dexec.cleanupDaemonThreads=false` (or put cleanupDaemonThreads in the exec plugin's config section in pom.xml)

**Comment by minborg** [comment]
Yes, you are right about that. I tried that too but classified that solution as "sweeping the problem under the carpet" as the Thread reported itself alive despite being interrupted. Also, we hade to go through about 50 cases in all the different demos.

**Comment by JerryShea** [comment]
Yep very fair

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
