### ISSUE TITLE
Cleanup ReferenceCounter/ReferenceCounted

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Core#111]
`ReferenceCounted` is an interface with the same methods as `ReferenceCounted` but surprisingly the latter does not implement the former.  There is a lack of documentation.

**Comment by minborg** [comment]
Runtime exceptions should not be declared.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
