### ISSUE TITLE
Flaky test JitterSamplerTest

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Core#114]
https://teamcity.chronicle.software/buildConfiguration/OpenHFT_ReleaseJob_ReleaseByArtifact/409814?buildTab=overview&showLog=409814_703_79.703

![image](https://user-images.githubusercontent.com/6506056/81903263-6ab5a900-95b9-11ea-91b7-81459e64342f.png)

**Comment by dpisklov** [comment]
ran 15000 times, never failed - probably there was some issue in the core itself?

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
