### ISSUE TITLE
Improved tracing of reference counting resources on branch

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#115]
Using branch ref

**Comment by peter-lawrey** [comment]
Replaced by https://github.com/OpenHFT/Chronicle-Core/issues/118 and others

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
