### ISSUE TITLE
Add a standardized way of reporting elapsed time

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Core#117]
In many of our libraries, we report various elapsed times (e.g. when a read took more than a certain amount of time). These reports vary greatly and are sometimes hard to read for a human.

These messages:
```
TcpEventHandler Non blocking read took 1856304 us.
MappedFile took 19291231 us to grow file /tmp/a.bin
FileShrinker run 93600 s ago.
```
Could instead be:
```
TcpEventHandler Non blocking read took 1.86 s (1856304123 ns)
MappedFile took 19.3 s (19291231113 ns) us to grow file /tmp/a.bin
FileShrinker run last 1 day and 2 hours (93600000000000 ns) ago.
```
We should have one human-readable form and another machine-readable form.

**Comment by peter-lawrey** [comment]
@minborg Your commit appears to unrelated to this issue. Do we still need this open?

**Comment by minborg** [comment]
I am closing this issue and will make a note to add it to future projects.
