### ISSUE TITLE
Enable better ReferenceCounted performance

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Core#127]
Some `ReferenceCounted` entities determine their close state by evaluating if `refCount < 1`. This might potentially delegate to slower methods such as `ConcurrentHashMap::size` or `IdentityHashMap::size`.

We could add a method `ReferenceCounted::isReleased` that is backed by an AtomicInteger, in turn, set by `releaseLast()`. 

![image](https://user-images.githubusercontent.com/7457876/84927485-33ad4880-b0cd-11ea-904d-51f9c08efb22.png)

**Comment by peter-lawrey** [comment]
This has been improved in DualReferenceCounted which caches the refCount.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
