### ISSUE TITLE
JLBH - Support throughput < 1 operation / s

### ISSUE THREAD

**Issue by danielmitterdorfer** [OpenHFT/Chronicle-Core#13]
I'd like to use JLBH for benchmarking bulk operations which may take more than 1 second to complete. In my case they take around  5 seconds, so want to specify a target throughput of less than 1/5 or 0.2 operations / second. However, the signature `JLBHOptions#throughput(int)` effectively prohibits target throughput rates of less than 1 operation / s. 

Are you open to support smaller target throughput rates? I could imagine an overloaded version with the signature `JLBHOptions#throughput(int, TimeUnit)` to specify the throughput per time unit and the default would be `TimeUnit.SECONDS`.

**Comment by peter-lawrey** [comment]
That sounds reasonable, would you be able to issue a Pull Request with your
suggested changes.

**Comment by danielmitterdorfer** [comment]
Hi Peter, thanks for your feedback. Then I'll look into it within the next few days.

**Comment by danielmitterdorfer** [comment]
@peter-lawrey I didn't find any docs on how to contribute. Do you require me to sign a CLA or something like that?

**Comment by peter-lawrey** [comment]
We naively assume that if you contribute to an Open Source project, you
don't expect money to change hands in the future either as a result.

**Comment by danielmitterdorfer** [comment]
Great. :)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
