### ISSUE TITLE
Add classes path in the class loader to the classpath

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#138]
Noether Maven nor Spring boot set the `java.class.path` correctly which prevents generated code form compiling.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
