### ISSUE TITLE
Add support for a ThreadIndexAssigner for assigning threads to a small number of ids

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#141]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.65](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.65), [BOM-2.20.80](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.80)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
