### ISSUE TITLE
EnumCache.initialSize behave consistently for static and dynamic enums

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Core#142]
And try to return the size of the array needed for no hash collisions.

So that EnumInterner can operate garbage free for static and dynamic enums.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.65](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.65), [BOM-2.20.80](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.80)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
