### ISSUE TITLE
Add a library announcer

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Core#144]
Whenever a Chronicle library, like Queue or Map, is first used in an application, it would be useful if certain information elements are output to the logs. This would greatly simplify the reconstruction of the software stack used. For example, upon detecting an anomaly or when analyzing old logs. The following information elements are proposed:

* Library name (e.g. Chronicle-Queue)
* Library version (e.g. 2.20.42)
* Java version
* Process id
* Library specific additional information (e.g. for datagrid: the used YAML configuration file and the server id)

Output to the log should be de-duplicated in order to reduce log clutter.

In view of this, I proposed that we add a common method in Core that outputs said information elements in a standardized way and that filters any attempts to output duplicate data.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.116](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.116), [BOM-2.20.161](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.161)
