### ISSUE TITLE
Changed AbstractCloseable to only be isClosed()=true after performClose() has been performed

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#145]
When close() is called isClosing() == true
if not closed, set to closing, if already closing and performCloseInBackground() == false, wait for closed
Finally set the isClosed() = true as performClose returns.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
