### ISSUE TITLE
Only waitForClosed() selectively to avoid deadlocks on shutdown

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#146]
If two thread wait for components to be closed and they can have nested component the result can be a dead lock.

**Comment by peter-lawrey** [comment]
This was fixed in https://github.com/OpenHFT/Chronicle-Core/issues/145

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.105](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.105), [BOM-2.20.139](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.139)
