### ISSUE TITLE
Make throwExceptionIfClosed() throw an exception if isClosing()==true

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#148]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.107](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.107), [BOM-2.20.141](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.141)
