### ISSUE TITLE
Add analytics coverage of code usage

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Core#150]
Include a system property to turn it off. Leave it on by default. As discussed in the dev meeting.

**Comment by minborg** [comment]
Merged as per https://github.com/OpenHFT/Chronicle-Core/commit/f983f7b50aef7250c810f8675bca8e013d6d85b4

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.116](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.116), [BOM-2.20.161](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.161)
