### ISSUE TITLE
Add Null checking where applicable

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Core#151]
Methods annotated by `@NotNull` should produce a `NullPointerException` if invoked by a `null` argument. As of now, only intent is indicated.

**Comment by minborg** [comment]
Methods annotated by `@NotNull` should produce a `NullPointerException` if invoked by a null argument. As of now, only intent is indicated.

**Comment by JerryShea** [comment]
If you compile in intellij then it automatically does this instrumentation
btw.

My dream is that the compiler can do all this for us i.e. confirm at
compile time that there are no callers that pass null to a Non I'll arg.

**Comment by JerryShea** [comment]
I believe the checkers framework is supposed to do this but I have not got
round to trying it recently

**Comment by minborg** [comment]
I have filed: https://github.com/osundblad/intellij-annotations-instrumenter-maven-plugin/issues/53

**Comment by JerryShea** [comment]
I'm not 100% convinced. I don't know if we should be weaving in extra stuff
to production code

**Comment by minborg** [comment]
I understand your concerns @JerryShea 

However, I think that it is better to immediately throw an exception if the invariants of the method do not hold rather than detecting the problem at a later stage, in some unlikely cases even in another thread. The JIT compiler is able to inline the assertions if stacked. This is equivalent to using the ubiquitous `Objects::requireNonNull` which is widely seen as uncontroversial. 

The compiler still needs to do null checking under the hood so it is likely that the performance impact is negligible.

I think we should do some benchmarking once we have a working candidate up and running to confirm this before we merge this potential feature with the master branch.

**Comment by minborg** [comment]
After some consideration, I agree with you @JerryShea . There are some potentially dangerous corner cases that may be affected by instrumentation. It is better to explicitly use `Objects.requireNonNull()` where applicable.
