### ISSUE TITLE
Fix potentially nasty rounding error in unsafe operations

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Core#152]
Arithmetic operations involving two ints are performed with `int` precision and when a `long` result is expected, widening takes place *after* computation. Thus, the result of adding two positive int values might be negative and subsequent use of the result with Unsafe operations might be disastrous. 

At least one of the `int` operands should be cast to `long` before these types of operations.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.116](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.116), [BOM-2.20.161](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.161)
