### ISSUE TITLE
Add factory methods for sets and maps for CoreDynamicEnum

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#155]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.21ea8](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.21ea8), [BOM-2.21ea21](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea21)
