### ISSUE TITLE
Invert the chronicle.analytics.enable system property

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Core#161]
and use `chronicle.analytics.disable` instead.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.122](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.122), [BOM-2.20.192](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.192)
