### ISSUE TITLE
Detect and record the first occurrence of a resource being used incorrectly.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#162]
A resource used incorrectly will eventually cause a program to fail however this doesn't show when it first had a problem.

Add code to trace the original cause of the error and fail sooner when using a resource incorrectly.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.123](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.123), [BOM-2.20.193](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.193)
