### ISSUE TITLE
Memory.nativeMemoryUsed() doesn't account mapped memory

### ISSUE THREAD

**Issue by leventov** [OpenHFT/Chronicle-Core#17]
Maybe there should be `OS.nativeMemoryUsed()` which accounts direct allocated memory as well as memory allocated via `OS.map()` (with flavours).

**Comment by peter-lawrey** [comment]
We couls look at /proc/self/maps but would have to decide which memory
mappings to include.

**Comment by leventov** [comment]
IMO it's an overkill. Similarly you cannot rely on the current `Memory.nativeMemoryUsed()`, because you are not guaranteed that everybody allocates memory only though Chronicle Core's `Memory.allocate()`, not unsafe directly.

What I want to add is merely statistics of `OS.map()` usage, the same as `Memory.nativeMemoryUsed()` is statistics of `Memory.allocate()` usage.

**Comment by peter-lawrey** [comment]
Fair point. Will see what we can do.

**Comment by peter-lawrey** [comment]
Can you have a look at 
https://github.com/OpenHFT/Chronicle-Core/commit/67e58c856c038206069e60496e46361e3a735761#diff-caa8ec7352ca32652b1077fc0d578f86

**Comment by leventov** [comment]
@peter-lawrey thanks

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
