### ISSUE TITLE
CleanerServiceLocator simplification

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Core#176]
investigate if the net.openhft.chronicle.core.cleaner.CleanerServiceLocator can be simplified. This code is called from:

![image](https://user-images.githubusercontent.com/6506056/102346357-9efda780-3f96-11eb-9ba5-7f2f7cd1507d.png)

**Comment by JerryShea** [comment]
Yep and net.openhft.chronicle.core.cleaner.CleanerServiceLocator#cleanerService is not thread-safe either

**Comment by minborg** [comment]
The method `CleanerServiceLocator:: cleanerService ` appears to be thread-safe as it is synchronized

**Comment by minborg** [comment]
@RobAustin In what perspective would you like a simplification?

**Comment by RobAustin** [comment]
@minborg -I suggest speaking with @peter-lawrey for suggestions on this.

**Comment by minborg** [comment]
I am closing this as it appears simple now. Services are internalized for some time.
