### ISSUE TITLE
make CleaningThreadLocal declared as static possible

### ISSUE THREAD

**Issue by pedegie** [OpenHFT/Chronicle-Core#182]
Hello, I have noticed that resources are not clean if we declare CleaningThreadLocal as static field, because on each cleanup, its cleanup function is nulled. In case of ten of thousands objects which use this class there is really huge overhead to keep all these references. What is the reason of setting cleanup function to null after cleanup? Also with java.lang.ThreadLocal there is no problem with static fields, could it be possible to implement this class to behave in the same way?

**Comment by peter-lawrey** [comment]
This has been fixed.  #223
