### ISSUE TITLE
Test build 2

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Core#183]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20ea127](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20ea127), [BOM-2.20.227](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.227)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20ea127](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20ea127), [BOM-2.20.230](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.230)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20ea127](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20ea127), [BOM-2.21ea1](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea1)
