### ISSUE TITLE
Added a Builder<T> interface to improve consistency of our builders

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#185]

**Comment by minborg** [comment]
A `Builder` should be more thoroughly specified. For example, there is a conceptual difference between a `Builder` and a `Factory` in the way that a Builder's `build()` method can typically only be invoked at most once whereas a Factory can be invoked any number of times.

A `Supplier` is generally considered a Factory so, in my opinion, a `Builder` should not extend `Supplier`. If a `Supplier` is needed one could instead provide `builder::build`.

Hence, a `Builder` must either prevent its build method from being invoked more than one time or it must make defensive copies of its internal state (if using transitive mutable states such as maps, lists etc) each time it produces an instance.

**Comment by minborg** [comment]
Would it be possible to expand the concept and support builders that throw a checked exception like `IOException` upon `build()`? Adding `throws Exception` to the `build()` method would require non-throwing builders to override the method. Another alternative would be to introduce `ThrowingBuilder extends Builder`
