### ISSUE TITLE
CleaningThread.cleanup to remove cleaned up ThreadLocals

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#191]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.21ea13](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.21ea13), [BOM-2.21ea39](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea39)
