### ISSUE TITLE
Added waitForCloseablesToClose for tests instead of waiting a fixed time

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#204]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.21ea25](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.21ea25), [BOM-2.21ea63](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea63)
