### ISSUE TITLE
ARMMemory initialization might cause deadlock

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Core#222]
Referencing the subclass `ARMMemory` from its superclass `UnsafeMemory` initializer might lead to class loading deadlock. 

I suggest moving `ARMMemory` to a separate (internal) class.

**Comment by minborg** [comment]
`ARMMemory` can not inherit from `UnsafeMemory` if `UnsafeMemory` creates `ArmMemory` in static code. Ideally, there should be a separate holder of the preferred memory model (in a separate class).

**Comment by peter-lawrey** [comment]
`ARMMemory` was package local, now private so it can only be called from the static initlizer block of UnsafeMemory. The initializer block is thread safe as it can only be called by one thread.
