### ISSUE TITLE
Add support for null objects to access native memory required by Chronicle-Algorythms.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#234]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.21ea82](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.21ea82), [BOM-2.21ea195](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea195)
