### ISSUE TITLE
Fixed on heap memory alignment issue for M1 mac ( and ARM )

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Core#235]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.21ea82](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.21ea82), [BOM-2.21ea195](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea195)
