### ISSUE TITLE
Support converting to a DynamicEnum without a String constructor

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#237]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.21ea83](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.21ea83), [BOM-2.21ea204](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea204)
