### ISSUE TITLE
ClassLookup deprecation

### ISSUE THREAD

**Issue by amichair** [OpenHFT/Chronicle-Core#25]
The ClassLookup class has recently been marked as @Deprecated, however there is no explanation or documentation on what to use as an alternative. One might think they could use ClassAliasPool directly, but it has no public constructor, so it is unclear how to migrate away from the deprecated class.

**Comment by peter-lawrey** [comment]
Good point, this needs to be documented better.
ᐧ

**Comment by RobAustin** [comment]
we have removed its deprecation as we have no plan to replace it in the short term
