### ISSUE TITLE
Add gcAndWaitForCloseablesToClose

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#250]
This method cleans the current thread's thread local resources, triggers a GC, waits for the finalizer to run so it can be checked and gives a chance for all the resources to be closed.

This wraps up a number of tasks a test needs to wait for on completion to ensure all resources are closed appropriately.

**Comment by peter-lawrey** [comment]
Also add tracing on resources created for ThreadLocal but not in a CleaningThread

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.22ea7](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.22ea7), [BOM-2.22ea29](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea29)
