### ISSUE TITLE
Enable throttling of memory mapping when they are running low on 64-bit systems.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#253]
This is needed to prevent running out of virtual memory is is unrecoverable for the JVM.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.22ea8](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.22ea8), [BOM-2.22ea29](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea29)
