### ISSUE TITLE
Add a message on how to get information on the latest releases and patches

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Core#256]
The Announcer could add a one-time message in conjunction with showing the JVM version.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.22ea12](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.22ea12), [BOM-2.22ea48](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea48)
