### ISSUE TITLE
ClassAliasPool.addAlias() causes name collisions and deserialization failure

### ISSUE THREAD

**Issue by amichair** [OpenHFT/Chronicle-Core#26]
The `addAlias` method uses `Class.getSimpleName()`, which is far from unique. Especially considering inner classes and enums which often use the same name (e.g. 'Type') and are supposed to be distinguished by the containing class name. This causes serialization/deserialization to fail due to a mixup between classes with the same simple name (e.g. said enums).

FWIW, as a workaround we use something like
`cls.getName().replaceAll("(\\w)\\w*\\.", "$1").replace('$', '.')` which has more chances of being unique, yet is still pretty short, along with the overloaded `addAlias` that takes a name per class. Maybe you can use a similar default instead of the class simple name.

**Comment by peter-lawrey** [comment]
Agreed, we should have a strategy for supporting nested classes with a
simple alias.

Can you include some examples of mapping you think would work?  I highly
recommend avoiding having the same class name with different outer classes.
This is much the same as having two packages with the same class name. At
this point you really need to have your own alias.
ᐧ

**Comment by amichair** [comment]
I'm not sure what other examples you mean - I specified one in the original description. It takes the first letter of each part of the package name, concatenates them with the top-level class name, and for inner classes adds a period and the inner class name. Not 100% unique but much closer to it in practice than just the simple class name.

As for naming inner classes, perhaps it's a matter of taste, but I disagree. It makes sense to have enums such as Asset.TYPE and User.TYPE in different classes. Much cleaner than a redundant Asset.ASSET_TYPE and User.USER_TYPE or something like that... for the same reason I would think it's redundant to have a User.userId field rather than User.id. I also see no problem with having the same top-level class name used in different packages - there is no need to duplicate the name of the package in the name of the class, or pick a sub-optimal class name just because some other package has a class with the desired name imho.

Again, this may be a matter of taste, but in any case it does happen in practice so the class-handling code should probably deal with it properly.

**Comment by peter-lawrey** [comment]
The aliases on apply to classes rather than fields.

So you could have

class User {
    class Type {
    }
}

and

class Asset {
    class Type {
    }
}

However, I would prefer to have a UserType and AssetType. esp as there is
already a built in Type interface.

In many cases the default pattern isn't suitable so you can add your own
alias such as

ClassAliasPool.CLASS_ALIASES.addAlias(ByteStore.class, "!binary");

ᐧ

**Comment by amichair** [comment]
I understand aliases do not apply to fields, I was just making a point about naming conventions (the rational behind naming members without redundancy is the same, whether they are fields, enums or inner classes). 

By the way, as an anecdote, I see  6 different top-level Type classes in different packages in the java.* core namespace... so even for top-level classes it seems to be standard practice to use the same names in different places. All the more reason to properly support this.

I do add custom aliases using the addAlias overload, as I mentioned originally - using the naming scheme in the code snippet I quoted. I was just suggesting maybe you should use something like that as a better default rather than getSimpleName, since the latter has a much higher chance of collisions in practice. This is what this issue is about.

**Comment by peter-lawrey** [comment]
I see your point and this would reduce collisions but at the cost of making
the aliases more cryptic.

One of the uses for alias is moving classes between packages or renaming
them and still being able to deserialize data written earlier of by a
system with an older version of the code.
ᐧ

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
