### ISSUE TITLE
Add a convenience method that checks a parameter for null and throws an IllegalArgumentException

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Core#264]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.22ea13](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.22ea13), [BOM-2.22ea49](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea49)
