### ISSUE TITLE
Remove conveniency method

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Core#266]
Remove the newly introduced IAE throwing method as we always use NPEs.

**Comment by minborg** [comment]
See https://github.com/OpenHFT/Chronicle-Core/issues/264

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.22ea14](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.22ea14), [BOM-2.22ea51](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea51)
