### ISSUE TITLE
Closeable.closeQuietly doesn't close AutoCloseable

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Core#268]
closeQuietly only recognizes java.io.Closeable, not its parent java.lang.AutoCloseable

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.22ea14](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.22ea14), [BOM-2.22ea51](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea51)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.21.93](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.21.93), [BOM-2.21.241](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21.241)
