### ISSUE TITLE
Alow unregistering of shutdown hook

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Core#278]
In `net.openhft.chronicle.core.shutdown.PriorityHook#clear` we should de-register shutdown hook to ensure our classes may be unloaded.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.22ea17](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.22ea17), [BOM-2.22ea69](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea69)
