### ISSUE TITLE
ClassLocal prevents Chronicle from unloading from classloader

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Core#281]
If a mapping of Java lang type -> Chronicle object is put to `ClassLocal` retained in a static field, such as `java.lang.Integer` -> `SerializationStrategies#ANY_SCALAR`, then Chronicle classes may not be unloaded from `ClassLoader` and `ClassLoader` will never be reclaimed by GC.

See https://bugs.openjdk.java.net/browse/JDK-8136353

**Comment by peter-lawrey** [comment]
ClassLocal is a Chronicle class so while it is used for anything, it will prevent core from being unloaded.

**Comment by alamar** [comment]
The user may expect that our libraries may unload when no longer needed, when in fact this won't happen.

**Comment by alamar** [comment]
Was it fixed @yevgenp ?

**Comment by yevgenp** [comment]
@alamar Peter's comment implies it's by design.
