### ISSUE TITLE
PriorityHook may be a bug

### ISSUE THREAD

**Issue by cubita-io** [OpenHFT/Chronicle-Core#282]
![image](https://user-images.githubusercontent.com/59306969/143418956-9ce09ee3-1196-4ca3-bffb-f0e380715350.png)
hooklets is PriorityQueue;

public class Test {

    public static void main(String[] args) {
        PriorityQueue<Integer> queue = new PriorityQueue<>();
        queue.add(1);
        queue.add(3);
        queue.add(2);
        queue.add(4);
        queue.add(6);

        for (Integer a : queue) {
            System.out.println(a);
        }
    }

}

result: 1 3 2 4 6
expect: 1 2 3 4 6

**Comment by alamar** [comment]
Thank you @cubita-io for noticing this!

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.22ea17](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.22ea17), [BOM-2.22ea69](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea69)
