### ISSUE TITLE
Reduce the number of issues marked as minor

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Core#289]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.22ea18](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.22ea18), [BOM-2.22ea71](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea71)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.22ea18](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.22ea18), [BOM-2.22ea72](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea72)
