### ISSUE TITLE
Deprecate ThreadLocalProperties

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Core#294]
Move this class to an internal package where it is used.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.22ea22](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.22ea22), [BOM-2.22ea79](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea79)
