### ISSUE TITLE
Document certain classes as thread-confined

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Core#309]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.22ea20](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.22ea20), [BOM-2.22ea73](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea73)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.22ea22](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.22ea22), [BOM-2.22ea79](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea79)
