### ISSUE TITLE
Correct NanoSample documentation

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Core#313]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.22ea21](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.22ea21), [BOM-2.22ea74](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea74)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.22ea22](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.22ea22), [BOM-2.22ea79](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea79)
