### ISSUE TITLE
Create a tmp directory if one doesn't exists or is read only

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#315]
Some build systems have a read-only tmp directory (for the build agent)
For this reason, a `tmp` directory under TARGET should be created if needed.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.22ea31](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.22ea31), [BOM-2.22ea122](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea122)
