### ISSUE TITLE
Add a new method AbstractCloseable:assertCloseable

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Core#320]
Some resources that provide guarantees that certain operations will always succeed (eg Map that has an update lock) must be able to prevent resources from being closed. 

This cannot be implemented easily as `AbstractCloseable::close` will CAS its state variable regardless and cannot (rightfully) be overridden.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.22ea22](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.22ea22), [BOM-2.22ea79](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea79)
