### ISSUE TITLE
AbstractReferenceCounted REFERENCE_COUNTED_SET must be guarded by synchronization

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Core#327]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.22ea23](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.22ea23), [BOM-2.22ea86](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea86)
