### ISSUE TITLE
Added marker interface so the library knows an implementation will ignore everything

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#347]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.23ea0](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.23ea0), [BOM-2.22.129](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22.129)
