### ISSUE TITLE
OS.java map() method limits Windows to 4GB.

### ISSUE THREAD

**Issue by SteveShell** [OpenHFT/Chronicle-Core#35]
chronicle.core.OS.java does not check for 64 Bit Windows OS.

    public static long map(@NotNull FileChannel fileChannel, FileChannel.MapMode mode, long start, long size)
            throws IOException, IllegalArgumentException {
        if (isWindows() && size > 4L << 30)
            throw new IllegalArgumentException("Mapping more than 4096 MiB is unusable on Windows, size = " + (size >> 20) + " MiB");

**Comment by tomshercliff** [comment]
@RobAustin I tried changing this locally to:
if (isWindows() && !is64Bit() && size > 4L << 30)

Unfortunately, this did seem to cause JVM to crash with an access violation (see below) when size > 4GB, so I'm reluctant to commit this.

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00000000511259f1, pid=12164, tid=0x00000000000008d4
#
# JRE version: Java(TM) SE Runtime Environment (8.0_162-b12) (build 1.8.0_162-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.162-b12 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# V  [jvm.dll+0x2759f1]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\cygwin64\home\Tom\Chronicle\Chronicle-Map\hs_err_pid12164.log
Compiled method (nm)    1949  922     n 0       sun.misc.Unsafe::setMemory (native)
 total in heap  [0x0000000003231050,0x00000000032313b8] = 872
 relocation     [0x0000000003231170,0x00000000032311b8] = 72
 main code      [0x00000000032311c0,0x00000000032313b8] = 504
Compiled method (c1)    1949  921       3       sun.misc.Unsafe::setMemory (10 bytes)
 total in heap  [0x00000000032313d0,0x00000000032317e8] = 1048
 relocation     [0x00000000032314f0,0x0000000003231528] = 56
 main code      [0x0000000003231540,0x00000000032316c0] = 384
 stub code      [0x00000000032316c0,0x0000000003231768] = 168
 metadata       [0x0000000003231768,0x0000000003231770] = 8
 scopes data    [0x0000000003231770,0x00000000032317a0] = 48
 scopes pcs     [0x00000000032317a0,0x00000000032317e0] = 64
 dependencies   [0x00000000032317e0,0x00000000032317e8] = 8
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

**Comment by RobAustin** [comment]
does it still fail if you run with 

-XX:-UseCompressedOops

**Comment by RobAustin** [comment]
@tomshercliff in which case, the check as is for the moment is correct. Currently we only support up to 4GB on windows even if  windows is running on 64bit.  [  I agree that fixing it so that we can run with more than 4GB on windows should be addressed ] but currently the check is correct, so I'm closing the issue as wont fix.
