### ISSUE TITLE
Added support for generic return types from GenericReflection.getReturnType()

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#351]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.23ea0](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.23ea0), [BOM-2.22.129](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22.129)
