### ISSUE TITLE
Mocker to try tClass.getClassLoader() and ClassLoader.getSystemClassLoader()

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#352]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.23ea0](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.23ea0), [BOM-2.22.129](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22.129)
