### ISSUE TITLE
Create ChronicleInit mechanism to set system properties before any of them are read by static initializers

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Core#354]
This class should have a static initialization block (which may be replaced via "monkey patching") and should also be supplied via system property to provide an implementation of the earliest initialization code.

**Comment by minborg** [comment]
Generally speaking, we should not use static variables. There are many disadvantages with the concept including thread safety issues, deadlocks, unclear order of initialization and problems with testing and mocking.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.23ea4](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.23ea4), [BOM-2.23ea6](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea6)
