### ISSUE TITLE
Fix a Thread safety issue in EnumInterner

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#356]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.23ea22](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.23ea22), [BOM-2.23ea80](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea80)
