### ISSUE TITLE
StringUtils.extractChars can be inefficient in java9+ runtimes

### ISSUE THREAD

**Issue by epickrram** [OpenHFT/Chronicle-Core#36]
`StringUtils.extractChars` currently returns a `char[]`; since java9, strings can be represented as ascii bytes, so a conversion is required between `byte[]` and `char[]`.

Current implementation allocates a new `char[]` and performs a per-byte copy.

Refers to #15

**Comment by peter-lawrey** [comment]
We need a interface which performs the String to/from raw memory operations
and has two implementations.

**Comment by epickrram** [comment]
Also raises a rather nasty possibility of serialising a String in one JVM running java9, then deserialising in a JVM running java8...

**Comment by peter-lawrey** [comment]
As long as the caller doesn't need to know the underlying storage of a
CharSequence e.g. raw memory, byte[], or char[] this is fine.

**Comment by MartyIX** [comment]
@epickrram This issue can be closed as JDK 8 uses `char[]` and JDK 9 uses `byte[]`.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
