### ISSUE TITLE
Make OS.getHostname() and OS.getIPAddress() more portable

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#362]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.23ea5](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.23ea5), [BOM-2.23ea11](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea11)
