### ISSUE TITLE
Add fallback System Properties for Greeting messages

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Core#364]
GraalVM native images does not define the system properties:

* `java.runtime.name`
* `java.runtime.version`

We could add fallback for these under the keys:

* `java.vm.name`
* `java.vm.version`

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.23ea6](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.23ea6), [BOM-2.23ea14](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea14)
