### ISSUE TITLE
Wrong exception type thrown when Windows/OSX attempts to look up an existing class with the wrong case

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Core#372]
When Windows and OSX attempt to look up an existing class with the wrong case, they throw a `NoClassDefFoundError` instead of `ClassNotFoundException`

This means `ClassAliasPool#forName` throws an unexpected error in these circumstances

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.23ea8](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.23ea8), [BOM-2.23ea25](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea25)
