### ISSUE TITLE
Make exception assertion code reusable

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Core#374]
We have code to assert on the presence or absence of exceptions everywhere in our codebase. We should make this reusable to remove the repetition.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.23ea9](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.23ea9), [BOM-2.23ea27](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea27)
