### ISSUE TITLE
Added simple wget

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Core#376]
see net.openhft.chronicle.core.io.Wget

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.23ea9](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.23ea9), [BOM-2.23ea27](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea27)
