### ISSUE TITLE
Add a ThreadConfinementAsserter that is always enabled regardless of -ea state

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Core#381]
This is needed for constructs relying on an always-on behaviour.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.23ea9](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.23ea9), [BOM-2.23ea27](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea27)
