### ISSUE TITLE
Jvm.resetExceptionHandlers() switches startup() handler from PERF to DEBUG

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Core#384]
It is assumed that reset would return the exception handlers to what they were set to initially

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.23ea10](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.23ea10), [BOM-2.23ea29](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea29)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.22.34](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.22.34), [BOM-2.22.135](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22.135)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.21.96](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.21.96), [BOM-2.21.265](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21.265)
