### ISSUE TITLE
Negative number of "resources to clean" reported

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Core#386]
When running software.chronicle.fix.router.integration.IntegrationRouterTest

> [main] INFO net.openhft.chronicle.core.io.BackgroundResourceReleaser - Still got -120 resources to clean

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.23ea11](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.23ea11), [BOM-2.23ea37](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea37)
