### ISSUE TITLE
OS getProcessId() slow is reverse DNS not setup correctly.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#40]
Migrated from https://github.com/OpenHFT/Chronicle-Queue/issues/380

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
