### ISSUE TITLE
Thread safety issue in AbstractReferenceCounted

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Core#401]
The Java memory model does not specify any special visibility rules for memory mutated when threads die. Thus, mutations with normal memory semantics might not be visible to other threads regardless if the mutating thread is alive or not.

Yet, this is assumed in `AbstractReferenceCounted::threadSafetyCheck`:

<img width="764" alt="image" src="https://user-images.githubusercontent.com/7457876/171392529-408f45de-079c-40c8-a7d3-5e9563bb9b6a.png">

Generally, if an entity with normal memory semantics has been used by one thread, it cannot be used by another thread unless memory barriers are used.

**Comment by minborg** [comment]
We might consider a `handoff()` method that can safely handoff an entity from one thread to another.

**Comment by peter-lawrey** [comment]
Fixed by https://github.com/OpenHFT/Chronicle-Core/issues/409
