### ISSUE TITLE
Improve doco of system properties

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Core#402]
Re: https://github.com/OpenHFT/Chronicle-Core/#system-properties-from-file

This doco is out of date - there is an alternative to calling Jvm.init() in a static block - we can use Jvm.getInteger etc. as added by @alamar for #354

It would be also useful to refer to the javadoc for Chronicle's opinionated boolean system properties - `net.openhft.chronicle.core.Jvm#getBoolean(java.lang.String)`

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.23ea22](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.23ea22), [BOM-2.23ea80](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea80)
