### ISSUE TITLE
Add code to check power management on linux

### ISSUE THREAD

**Issue by maxim-ponomarev** [OpenHFT/Chronicle-Core#405]
See [Chronicle Queue #807](https://github.com/OpenHFT/Chronicle-Queue/issues/807) for details.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.23ea20](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.23ea20), [BOM-2.23ea72](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea72)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.23ea32](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.23ea32), [BOM-2.23ea111](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea111)
