### ISSUE TITLE
Assertions erroneously guards against null objects for certain unsafe operations

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Core#407]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.23ea13](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.23ea13), [BOM-2.23ea69](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea69)
