### ISSUE TITLE
Added SingleThreadedChecked to make resetting and disabling this check more consistent

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#409]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.23ea20](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.23ea20), [BOM-2.23ea72](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea72)
