### ISSUE TITLE
Added support for annotation aliases to make them simpler

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#412]
E.g.
```java
@LongConvertion(Base85LongConverter.class)
@interface Base85 {
}

@Base85 long symbol;

public void symbol(@Base85 long symbol) {
   this.symbol = symbol;
}
```

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.23ea20](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.23ea20), [BOM-2.23ea72](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea72)
