### ISSUE TITLE
SetTimeProvider should support setting time in micros and nanos and advancing time

### ISSUE THREAD

**Issue by gordonnb** [OpenHFT/Chronicle-Core#42]
Primarily for testing purposes and to provide MiFID II support.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
