### ISSUE TITLE
Use a relative path for tmp and target if appropriate.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#430]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.23ea23](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.23ea23), [BOM-2.23ea90](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea90)
