### ISSUE TITLE
Added ClosedIORuntimeException

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#436]
To distinguish from other IORuntimeExceptions

**Comment by peter-lawrey** [comment]
@alamar can you run this locally to check it works for a language other than English?

**Comment by peter-lawrey** [comment]
Further work https://github.com/OpenHFT/Chronicle-Network/issues/201

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.23ea28](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.23ea28), [BOM-2.23ea104](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea104)
