### ISSUE TITLE
Don't check if the current thread is alive

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#438]
This is surprisingly expensive to do

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.23ea32](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.23ea32), [BOM-2.23ea111](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea111)
