### ISSUE TITLE
Add ability to listen for the addition and removal of references to a reference counted object

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Core#444]
This will support the ReferenceCountedCache to trigger flushes in a timely manner on the resources it is managing

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.22.35](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.22.35), [BOM-2.22.158](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22.158)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.23ea34](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.23ea34), [BOM-2.23ea121](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea121)
