### ISSUE TITLE
DualReferenceCounted introduces risk of deadlock

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Core#445]
`DualReferenceCounted` wraps an instance of `VanillaReferenceCounted` and one of `TracingReferenceCounted`, delegating all calls that change state (e.g. `reserve`/`release`/`releaseLast`) to both of them. These calls are made in synchronized blocks so as to ensure both child `ReferenceCounted` objects are called in sequence atomically.

This presents a number of issues, 
- If one of the calls fails, the two `ReferenceCounted`s can get out of sync (this currently happens if you called `releaseLast`, with a reference that isn't the last)
- The `onRelease` handler in the children are called in the synchronized block, [introducing the possibility of a deadlock](https://github.com/OpenHFT/Chronicle-Core/blob/e243bfa5095657d6e3ecc877a6302bec41f2c13e/src/main/java/net/openhft/chronicle/core/io/TracingReferenceCounted.java#L121)

[The addition of the ReferenceChangeHandler](https://github.com/OpenHFT/Chronicle-Core/pull/443) adds to this risk. I propose we deprecate `DualReferenceHandler` and use either `TracingReferenceHandler` or `VanillaReferenceHandler` individually depending on if tracing is turned on.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.22.35](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.22.35), [BOM-2.22.158](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22.158)
