### ISSUE TITLE
JvmTest fails on MacOS X with Intel processor

### ISSUE THREAD

**Issue by pcoppinger** [OpenHFT/Chronicle-Core#451]
Running the "test" target generates the following error on my machine:

[ERROR] Tests run: 20, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 1.691 s <<< FAILURE! - in net.openhft.chronicle.core.JvmTest
[ERROR] net.openhft.chronicle.core.JvmTest.getCpuClass  Time elapsed: 0.288 s  <<< FAILURE!
org.junit.ComparisonFailure: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz expected:<[Apple M1]> but was:<[Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz]>
	at net.openhft.chronicle.core.JvmTest.getCpuClass(JvmTest.java:291)

Root cause is in Boorstrap.java, line 72:

    static boolean isMacArm0() {
        return OS_NAME.equals("Mac OS X");
        // TODO FIX && CpuClass.CPU_MODEL.startsWith("Apple M");
    }

I have noticed that because isMacArm0() erroneously returns true on my machine, there are several errors that also occur in Chronicle-Bytes. I will report these errors seperately.

**Comment by JerryShea** [comment]
@pcoppinger can you advise what values the various constants in `Bootstrap` including `CpuClass#CPU_MODEL` have on your machine? If you configure your logger with `net.openhft.chronicle.core.Bootstrap=DEBUG` do you see any debug messages?

Feel free to submit a PR if you can make it work on your machine

**Comment by alamar** [comment]
@JerryShea `os.arch=x86_64`

**Comment by JerryShea** [comment]
@pcoppinger pls try https://github.com/OpenHFT/Chronicle-Core/pull/459

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.24ea1](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.24ea1), [BOM-2.24ea8](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea8)
