### ISSUE TITLE
Warning if running under Java >= 11 to point user to command line flags doco

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Core#457]
As customers do not necessarily know about these command line flags

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.24ea1](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.24ea1), [BOM-2.24ea8](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea8)
