### ISSUE TITLE
slf4j-simple properties in system.properties are ignored

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Core#469]
The fix for https://github.com/OpenHFT/Chronicle-Threads/issues/175 means that `Bootstrap` now eagerly loads `net.openhft.affinity.Affinity` and because that class creates a `Logger` it means that the logging framework is initialised.

This means if you e.g. slf4j-simple properties in your `system.properties` they are no longer used.

**Comment by alamar** [comment]
That's disappointing since I happen to regularly use slf4j-simple.

**Comment by JerryShea** [comment]
You can use simplelogger.properties as a workaround
