### ISSUE TITLE
JLBH does not work on Java9 runtimes

### ISSUE THREAD

**Issue by epickrram** [OpenHFT/Chronicle-Core#47]
Usage of Affinity and in particular BootClassPath is not yet supported.

**Comment by epickrram** [comment]
Updated affinity dependency to remove reference to URLClassPath

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
