### ISSUE TITLE
Add ServiceLoader-based runnable discovery to ChronicleInit

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Core#470]
In addition to property-based initialization it should be possible to use ServiceLoader/META-INF-based initialization.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.23.41](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.23.41), [BOM-2.23.151](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23.151)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.24ea5](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.24ea5), [BOM-2.24ea38](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea38)
