### ISSUE TITLE
De-duplicate toDouble implementation and expose it publicly

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Core#479]
We have two implementations of toDouble that do approximately the same thing. To avoid more being created we should standardise on one and make it reusable.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.23.43](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.23.43), [BOM-2.23.157](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23.157)
