### ISSUE TITLE
JLBH can be installed to run on event loop

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Core#49]
See https://github.com/OpenHFT/Chronicle-Core/commit/8d9914558b515ea8e5858b725b1ba0386768fcc7 and https://github.com/OpenHFT/Chronicle-Core/commit/bfc7184a85be9ad5207e8ead3b85866366e51ad6

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
