### ISSUE TITLE
UnsafeTextTest.testRandom is flaky

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Core#493]
https://teamcity.chronicle.software/buildConfiguration/Chronicle_BuildAll_Build/788240?buildTab=overview&hideProblemsFromDependencies=false&expandBuildTestsSection=true&hideTestsFromDependencies=false

>  Caused by: java.lang.AssertionError: 6.6174449004242214E-24 expected:<4.6751491878715573E-8> but was:<4.675149187871557E-8>

Likely cause is changes to Double handling

**Comment by JerryShea** [comment]
This is no longer flaky due to changes made for asDouble consolidation
