### ISSUE TITLE
Stop swallowing exceptions in close methods

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Core#499]
Previously we've caught exceptions in close methods, and logged them at debug level, effectively swallowing them. We should log exceptions at warning level to pick up bugs in close methods.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.23.45](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.23.45), [BOM-2.23.163](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23.163)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.24ea10](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.24ea10), [BOM-2.24ea47](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea47)
