### ISSUE TITLE
Jvm.pause to only use Thread.sleep

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#50]
LockSupport.parkNanos is sometime miil-seconds off on Windows (which for sub-milliseconds i bad)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
