### ISSUE TITLE
Add method to check whether running in core event loop

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Core#519]
Some of event loop users may need such check to make sure their methods are only called in thread safe fashion

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.24ea18](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.24ea18), [BOM-2.24ea62](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea62)
