### ISSUE TITLE
JVM crashes with SIGBUS + BUS_ADRERR

### ISSUE THREAD

**Issue by telles-simbiose** [OpenHFT/Chronicle-Core#52]
@peter-lawrey,

I ran into this JVM crash when running multiple JVMs (4 instances) in the same server:

```
Current thread (0x00007f6a60015800):  JavaThread "CommitLogFlushThread-0" daemon [_thread_in_Java, id=12927, stack(0x00007f6a1900e000,0x00007f6a1910f000)]

siginfo: si_signo: 7 (SIGBUS), si_code: 2 (BUS_ADRERR), si_addr: 0x00007f6a1e3aa000
```
(full log at: https://gist.github.com/telles-simbiose/58b91617eaadc82ae9c50279daab142c)

Right after the first crash, the other 3 instances also crashed, but doing different things in another thread

```
Current thread (0x00007f8134e46800):  JavaThread "BinaryDiffConsumerTask-0" [_thread_in_Java, id=12647, stack(0x00007f80dd6fe000,0x00007f80dd7ff000)]

siginfo: si_signo: 7 (SIGBUS), si_code: 2 (BUS_ADRERR), si_addr: 0x00007f80c93e3000
```
(full log at: https://gist.github.com/telles-simbiose/c6a96d01f2aa8b79924006acd8dc31a8, https://gist.github.com/telles-simbiose/9ba99522c7f1a127e065e40b62018393 and https://gist.github.com/telles-simbiose/f854c65996fa4bcf63535173dfd2a400)

I found out that BUS_ADRERR means that it accessed an invalid physical address and I am using addresses returned from `Memory.allocate` and `OS.map`.

Is there anyway for these methods to return an invalid address? Or for these addresses become invalid after some operation?

Thanks so much.

**Comment by dpisklov** [comment]
None of the gists contain stack traces, they all seem to be cut.
As such I see no reference to Chronicle code, and we can't advise on why it happens considering we see no stack trace.
I\m closing it as invalid, feel free to reopen if you can provide more meaningful stacktraces or (better) test case which shows this failure.

**Comment by dpisklov** [comment]
MEMORY.allocate calls Unsafe.allocateMemory, so unless Oracle's Unsafe returns invalid address (doubt it!) we are not modifying it in any way.

Can you create a test case which would reproduce this? Or is it only happening with 2 processes?

**Comment by telles-simbiose** [comment]
@dpisklov , just figured out what was causing the problem. It has actually nothing to do with Chronicle Core.

The problem is that the partition where my application was storing data was mounted as `tmpfs` with a very limited size. When this partition gets full, JVM crashes when trying to resize or create new files.

Thank you very much!
