### ISSUE TITLE
Reduce verbosity of license check messages

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Core#523]
So we have either
```
license for XXX expires in AAA days.
```
or
```
license for XXX expires in AAA days. At which point, this product will stop working....
```
if less than 30 days to run

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.24ea20](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.24ea20), [BOM-2.24ea69](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea69)
