### ISSUE TITLE
Don't use finalizers by default

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Core#536]
There are some Finalizers in the codebase to check resource management. This change ensures that they are only enabled explicitly

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.23.48](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.23.48), [BOM-2.23.178](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23.178)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.24ea21](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.24ea21), [BOM-2.24ea70](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea70)
