### ISSUE TITLE
Allow customisation of histograms

### ISSUE THREAD

**Issue by NickWard** [OpenHFT/Chronicle-Core#54]

**Comment by hft-team-city** [comment]
Released in Chronicle-Core-1.12.0 (https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-1.12.0), BOM-1.15.253 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.15.253)

**Comment by hft-team-city** [comment]
Released in Chronicle-Core-1.12.0 (https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-1.12.0), BOM-1.15.259 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.15.259)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
