### ISSUE TITLE
StringUtils startsWith and endsWith bounds check and unit tests

### ISSUE THREAD

**Issue by tgd** [OpenHFT/Chronicle-Core#551]
* Increase test coverage for `StringUtils` class
* `endsWith` and `startsWith` exhibit bug where if search string is longer than search string an exception is thrown. Fix by returning false if source string is shorter than the search string.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.24ea23](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.24ea23), [BOM-2.24ea74](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea74)
