### ISSUE TITLE
Add a createDirectories with better error messages

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#56]
If you have a broken link directory;
- File.mkdirs() return false without any error message.
- Files.createDirectories(path) complains the FileAlreadyExistsException which is confusing.

If a directory is read only
- File.mkdirs() return false without any error message.

If a file already exists with that name
- File.mkdirs() return false without any error message.
- Files.createDirectories(path) complains the FileAlreadyExistsException which is less confusing.

**Comment by hft-team-city** [comment]
Released in Chronicle-Core-1.12.8 (https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-1.12.8), BOM-1.15.318 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.15.318)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
