### ISSUE TITLE
Adjust the JLBH percentiles to include 99.7% and 99.97%

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#57]
Add the 99.7% and 99.97% values.

99% = 1 - 1/10^2
99.68% = 1 - 1/10^2.5
99.9% = 1 - 1/10^3
99.968% = 1 - 1/10^3.5
99.99% = 1 - 1/10^4

**Comment by hft-team-city** [comment]
Released in Chronicle-Core-1.12.8 (https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-1.12.8), BOM-1.15.318 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.15.318)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
