### ISSUE TITLE
Add "scoped" thread-locals

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Core#575]
There is a pattern that is repeated in our code whereby we use singleton thread-local resources to avoid creating garbage.

Some examples include
- [Wires.acquireBinaryWire](https://github.com/OpenHFT/Chronicle-Wire/blob/d0e7b1c47f84a62a91eefe9f4f1a49d7b49e0acd/src/main/java/net/openhft/chronicle/wire/Wires.java#L394)
- [Wires.acquireBytes](https://github.com/OpenHFT/Chronicle-Wire/blob/d0e7b1c47f84a62a91eefe9f4f1a49d7b49e0acd/src/main/java/net/openhft/chronicle/wire/Wires.java#L372)
- [Wires.acquireAnotherBytes](https://github.com/OpenHFT/Chronicle-Wire/blob/d0e7b1c47f84a62a91eefe9f4f1a49d7b49e0acd/src/main/java/net/openhft/chronicle/wire/Wires.java#L403)
- [Wires.acquireBytesForToString](https://github.com/OpenHFT/Chronicle-Wire/blob/d0e7b1c47f84a62a91eefe9f4f1a49d7b49e0acd/src/main/java/net/openhft/chronicle/wire/Wires.java#L382)
- [WireInternal.acquireStringBuilder](https://github.com/OpenHFT/Chronicle-Wire/blob/d0e7b1c47f84a62a91eefe9f4f1a49d7b49e0acd/src/main/java/net/openhft/chronicle/wire/WireInternal.java#L108)
- [WireInternal.acquireAnotherStringBuilder](https://github.com/OpenHFT/Chronicle-Wire/blob/d0e7b1c47f84a62a91eefe9f4f1a49d7b49e0acd/src/main/java/net/openhft/chronicle/wire/WireInternal.java#L113)
- [WireInternal.acquireStringBuilderForValueIn](https://github.com/OpenHFT/Chronicle-Wire/blob/d0e7b1c47f84a62a91eefe9f4f1a49d7b49e0acd/src/main/java/net/openhft/chronicle/wire/WireInternal.java#L326)
- [WireInternal.acquireStringBuilderForValueOut](https://github.com/OpenHFT/Chronicle-Wire/blob/d0e7b1c47f84a62a91eefe9f4f1a49d7b49e0acd/src/main/java/net/openhft/chronicle/wire/WireInternal.java#L330)
- [WireInternal.acquireInternalBytes](https://github.com/OpenHFT/Chronicle-Wire/blob/d0e7b1c47f84a62a91eefe9f4f1a49d7b49e0acd/src/main/java/net/openhft/chronicle/wire/WireInternal.java#L317)

As you can see they have proliferated because sometimes to avoid a usage-collision, being thread-local is not enough. Indeed there have been a few bugs that have been the result of a thread using it's thread-local bytes in an outer scope, then the same thread over-writing it in an inner scope.

One way to mitigate this risk is for threads to take a lease on these resources and then return them once they're done with them. While the lease is being held the resource should not be available to any other nested scope.

The proposed pattern is:

```java

try (ScopedResource<Bytes<?>> stlBytes = Wires.acquireScopedBytes()) {
    // Use the bytes for whatever (we are holding an exclusive lease on it)
    Bytes<?> bytes = stlBytes.get();
    bytes.append("Hello world: ");
    bytes.append(callSubMethodThatMightAlsoTryAndUseTheThreadLocal());
    valueOut.text(bytes);
} // <-- the bytes instance is returned to the "pool" and made available to other callers again
```

Following this approach would eliminate a class of errors, and worst-case, when the pool is not large enough, generate some garbage, though this should also generate a warning so the usage pattern can be reviewed.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.24ea27](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.24ea27), [BOM-2.24ea86](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea86)
