### ISSUE TITLE
Check that boolean is either true or false.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#59]
To reduce typos, boolean values are checked to be in any case

```
true
t
yes
y
```
or
```
false
f
no
n
```
Empty String is ok if parsing a Boolean.
Anything else may produce a warning or an error.

**Comment by hft-team-city** [comment]
Released in Chronicle-Core-1.12.8 (https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-1.12.8), BOM-1.15.318 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.15.318)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
