### ISSUE TITLE
Add support for explicit and optional safepoints

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#60]
Add
```
Jvm.safepoint();
// and
Jvm.optionalSafepoint();
```
to support adding safepoints explicitly.

Add test to ensure that a safepoint is performed, however it is very light weight. e.g. ~25 ns.

**Comment by hft-team-city** [comment]
Released in Chronicle-Core-1.12.8 (https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-1.12.8), BOM-1.15.318 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.15.318)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
