### ISSUE TITLE
Fixed safe point test

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Core#61]
see http://teamcity.higherfrequencytrading.com:8111/viewLog.html?buildId=255182&tab=buildResultsDiv&buildTypeId=OpenHFT_ChronicleCore_Snapshot

**Comment by hft-team-city** [comment]
Released in Chronicle-Core-1.15.2 (https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-1.15.2), BOM-1.15.348 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.15.348)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
