### ISSUE TITLE
Jvm.isMacArm() is failing on an M2 Mac

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Core#627]
<img width="479" alt="image" src="https://github.com/OpenHFT/Chronicle-Core/assets/6506056/af89a9fe-8ba4-4b5e-8c41-90e8c0e76624">

**Comment by jkolobok** [comment]
You are probably using x64 JVM&Rosetta2 instead of native ARM JVM. So the result is correct.
