### ISSUE TITLE
fixed net.openhft.chronicle.core.JvmSafepointTest

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Core#63]
This test net.openhft.chronicle.core.JvmSafepointTest fails on TC, see http://teamcity.higherfrequencytrading.com:8111/repository/download/OpenHFT_ReleaseJob_ReleaseByArtifact/257026:id/ReleaseAutomation/projects/chronicle-core-runTests-1527606961685.log

**Comment by peter-lawrey** [comment]
On a slow system the count expected needed to be lower. Fixed now.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
