### ISSUE TITLE
In DumpMain, class resolving takes 2/3 of execution time when queue value type not present

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Core#644]
Probably elsewhere. It turns out that Class.forName() is an expensive operation and should not be done repeatedly. Let us try caching the absense of the value to avoid redoing this lookup on every entry.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.25ea14](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.25ea14), [BOM-2.25ea45](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.25ea45)
