### ISSUE TITLE
Drop the use of a map to cache weak references to maps

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#65]
This cache is surprisingly expensive to maintain. See net.openhft.chronicle.bytes.jitter.MemoryReadJitterMain to show this is an issue.

**Comment by anirudh-striim** [comment]
When would a write to the REFERENCE_MAP happen ? Only at create time of the queue ?

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
