### ISSUE TITLE
Add a helper method to use Class.getPackageName()

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#662]
Java 9 has a more efficient method to obtain the Package name, but since Java 8 doesn't have this a less efficient `getPackage().getName()` has been used.

The purpose of this issue is to have a helper method which use getPackageName when available or caches the package name for Java 8.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.26ea1](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.26ea1), [BOM-2.26ea10](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.26ea10)
