### ISSUE TITLE
I do not understand how this project is released

### ISSUE THREAD

**Issue by smiklosovic** [OpenHFT/Chronicle-Core#668]
Looking into

https://repo1.maven.org/maven2/net/openhft/chronicle-core/

I see that there started to be these "ea" releases but there is never full release. How are people supposed to run their software stack with "not early access" library of Chronicle Core? Where are "full releases" like 2.25.0, 2.24.0 ... 

What does even "0" in "2.25ea0" mean?

I am from Apache Cassandra (nosql distributed database) and we are trying to make sense of this so we can use this software in a predictable manner.

**Comment by alamar** [comment]
2.25ea0 means first release (usually after breaking changes but before new functionality) in 2.25ea development branch.

Stable release buildss such as 2.25.52 are provided for Chronicle customers. The tags and the source code are still available via git.

**Comment by smiklosovic** [comment]
@alamar ok so when I fork this project and make a release to Maven Central on my own, that is all legal? That just seems like a hurdle to jump over.

**Comment by tgd** [comment]
Hi @smiklosovic - let me add some more context - the artifacts on maven central come from our development/ea branch. In my experience this is consumed by a large number of open source projects reliably (for our other artifacts too). This development/ea branch still goes through an extensive test suite prior to release. Releases from this branch will contain the latest features and bug fixes.

Many organizations use the “ea” release in production, as this contains the latest functionality and fixes.

You can view the stable versions that Ilya mentions as long term support releases for which we offer commercial support and backport bug fixes that are first applied to our development/ea branch in any case.

**Comment by tgd** [comment]
@smiklosovic some more commentary on this release methodology can be found here: 

https://chronicle.software/chronicle-25-whats-new-and-improved/

> **Our release methodology**
> 
> We’re often asked questions about our release methodology – our approach to EA releases draws the most questions of all. In our releases, EA stands for Early Access. Approximately every six months, we cut a new major release branch. This allows us to evolve the APIs of our products and still maintain versions with the old APIs until they are no longer supported. This provides continuity for those who need it, and faster change for those who opt-in for it.
> 
> When we first cut a new release branch we include the “ea” moniker in the release names, for example 2.26ea1. We keep releasing with this moniker until we consider the branch fully stable, at which point the “ea” moniker is removed, and the first official stable release of that release series is made. To put this into context, the x26 release was first released in May 2024; we anticipate this will evolve into a stable release in October 2024, coinciding with when the next early access release series will begin. Stable release access is offered to customers with a commercial agreement in place. For our open-source offerings all of our EA releases are available on [maven central](https://search.maven.org/search?q=net.openhft).
> 
> At any one time, it’s possible that we will support the current major release series and two older release series. At the time of writing, we have released x.26 early access but ship x.25 and x.24 stable release series regularly. Customers who receive support on these branches, and the stable release series will receive regular updates and back-porting of bug fixes. Note that many of the features listed in the article have also been backported to our stable branches for commercial customers so are available in EA and stable versions.
> 
> You can find more information about our versioning methodology in the [OpenHFT repository on Github](https://github.com/OpenHFT/OpenHFT/blob/ea/docs/Version-Support.adoc). If you’d like to learn more about getting access to our stable release series please [contact us](https://chronicle.software/contact-us/).

> Note: Many organizations use the “ea” release in production, as this contains the latest functionality and fixes.

**Comment by smiklosovic** [comment]
@tgd Thank you! Good to know that ea's are production ready. So I think that updating to the latest ea in a respective xN release is the best practice, correct?

**Comment by tgd** [comment]
Yep! That will get you the latest features and bug fixes that are in develop.

If you have any further questions please let us know

**Comment by smiklosovic** [comment]
@tgd 

Could you please elaborate on e.g. "2.26ea0" (ea0 is what I am looking at). So that is the very first release when you decided to start the development of 2.26?

Also, let's say that there is 2.25ea15 and you decided that this will be commercially supported so you release 2.25.0 for commercial purposes. When there is something to fix in 2.25.0, you create a patch, apply it to 2.25.1 and release that to your customers.

My question is, where do the fixes in 2.25.1 go? Into 2.25ea16? Or into 2.26eaX ?

**Comment by tgd** [comment]
> "2.26ea0" (ea0 is what I am looking at). So that is the very first release when you decided to start the development of 2.26?

Yes that is correct

> My question is, where do the fixes in 2.25.1 go? Into 2.25ea16? Or into 2.26eaX ?

Bug fixes will go to develop first and then be released in the next EA version (for now 2.26eaX, in other words `max($major).max($branch).ea++$prev_release_build_number`. We then backport applicable bug fixes into the non EA long term support releases.
