### ISSUE TITLE
OS.map increasing RSS memory

### ISSUE THREAD

**Issue by telles-simbiose** [OpenHFT/Chronicle-Core#67]
Hi there,

My software is having memory leak issues, while investigating I came up with this test:

```java
package br.com.s1mbi0se;

import net.openhft.chronicle.core.OS;
import org.junit.Test;

import java.io.File;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.nio.channels.FileChannel;

public class TestChronicleCore {

    @Test
    public void test() throws IOException, InterruptedException {
        final File file = File.createTempFile("test_", ".data");
        file.deleteOnExit();

        final RandomAccessFile raf = new RandomAccessFile(file, "rw");
        raf.setLength(4 * 1024 * 1024 * 1024L);

        final long[] addresses = new long[1000000];
        final int mapSize = 4 * 1024;

        final FileChannel fileChannel = raf.getChannel();

        for (long i = 0; i < addresses.length; i++) {
            addresses[(int) i] = OS.map(fileChannel, FileChannel.MapMode.READ_WRITE, mapSize * i, mapSize);
        }

        for (long i = 0; i < addresses.length; i++) {
            OS.unmap(addresses[(int) i], mapSize);
        }

        Thread.sleep(60 * 1000);
    }
}
```

I ran this code with these JVM flags: `-ea -Xms256M -Xmx256M -XX:+AlwaysPreTouch`, so that all heap space is already committed and touched by JVM and any changes to memory usage must be something off-heap.

When the program reaches the last command (Thread.sleep), the process is using around 522M of resident memory (RSS), while I expected it to be around 300M (that's how much memory it uses if I don't map anything). Please note that I am unmapping eveything before it reaches this line.

Is this a bug, am I using it incorrectly or is this somehow expected?

Thanks in advance.

**EDIT:**
This is output of `pmap -XX PID`: https://gist.github.com/telles-simbiose/d546c61c19da7e7b8b76e5f534b8d6d2

I think the issue is related to that mapping on address `d5580000`, its size changes according to the variables I use on this test (it uses more memory if I map more times)

**EDIT 2:**
I made this C program that should have the same behaviour as the Java program: https://gist.github.com/telles-simbiose/da0c8fc66b57078e7ef7fab3a5482b82
But this program does not have any memory leaks

**Comment by telles-simbiose** [comment]
This is output of `pmap -XX PID`: https://gist.github.com/telles-simbiose/d546c61c19da7e7b8b76e5f534b8d6d2

I think the issue is related to that mapping on address `d5580000`, its size changes according to the variables I use on this test (it uses more memory if I map more times)

**Comment by telles-simbiose** [comment]
@peter-lawrey , could you please take a look? Thanks so much

**Comment by dpisklov** [comment]
@telles-simbiose In your command line (from pmap) you override your own Xms settings:
`-Xms256M -Xmx256M -XX:+AlwaysPreTouch -Xmx2G`. Can you re-test with correct command line pls?

**Comment by dpisklov** [comment]
Closing as no response received. Feel free to reopen
