### ISSUE TITLE
Don't fill the stack trace when it will used for another thread

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#681]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.27ea2](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.27ea2), [BOM-2.27ea11](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.27ea11)
