### ISSUE TITLE
Introduced net.openhft.chronicle.core.Jvm#perf

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Core#72]

**Comment by dpisklov** [comment]
Do we still need this stuff at all? Why don't we use simple SLF4J loggers especially now that we have Chronicle Logger backend for it?

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
