### ISSUE TITLE
System alignment requirements violated

### ISSUE THREAD

**Issue by gco** [OpenHFT/Chronicle-Core#73]
Chronicle is writing Shorts to non-Short-aligned addresses causing the JVM to crash with a bus error.  Most RISC architectures require larger-than-byte memory accesses to be size-aligned.

--- called from signal handler with signal 10 (SIGBUS) ---
ffffffff7d976a7c Unsafe_SetShort (ffffffff7de68658, 1001ec800, ffffffff7abfad60, 4d, 2020, ffffffff7de68648) + 168
ffffffff6a01191c * sun/misc/Unsafe.putShort(Ljava/lang/Object;JS)V+0
ffffffff6a0118c0 * sun/misc/Unsafe.putShort(Ljava/lang/Object;JS)V+0
ffffffff6a008068 * net/openhft/chronicle/core/UnsafeMemory.writeShort(Ljava/lang/Object;JS)V+36
ffffffff6a0080b4 * net/openhft/chronicle/bytes/HeapBytesStore.writeShort(JS)Lnet/openhft/chronicle/bytes/HeapBytesStore;+32
ffffffff6a007f58 * net/openhft/chronicle/bytes/HeapBytesStore.writeShort(JS)Lnet/openhft/chronicle/bytes/RandomDataOutput;+8

See https://github.com/hazelcast/hazelcast/issues/5518 for a similar issue in a different project.

**Comment by gco** [comment]
ping.  This abuse of unsafe stores results in the JVM crashing.

**Comment by dpisklov** [comment]
We do not have any client suffering from this and we don't have hardware to reproduce/test.
PRs are welcome, otherwise our top priority are issues from our clients. If you are interested in fixing this ASAP you may consider purchasing the support agreement, for that please contact sales@chronicle.software

**Comment by gco** [comment]
Making these low-level primitives safe ended up exposing https://github.com/OpenHFT/Chronicle-Algorithms/issues/7 as the next set of failures in the OpenGrok tests.   Making the NativeAccess low-level primitives safe resulted in thousands of test failures in Chronicle-Algorithms.
