### ISSUE TITLE
In different versions of the JVM java.nio.Bits class the reservedMemory field is either an AtomicLong, a long or missing.

### ISSUE THREAD

**Issue by NickWard** [OpenHFT/Chronicle-Core#74]
We currently only account for the first case in the Jvm class.

**Comment by dpisklov** [comment]
@NickWard Can I have exact versions for which it is different? It is fine for all 8-9-11 versions I have, so I can't really test it.

**Comment by NickWard** [comment]
Testing in client with 1.8.0_65 on Windows. The Bits class in rt.jar does not have the field, but the Bits class in the src.zip has a long. Which is weird but we should account for it. Don't know at what point it gets changed to an AtomicLong.

**Comment by dpisklov** [comment]
@NickWard I think I fixed that - can you test this on Windows?

**Comment by NickWard** [comment]
@dpisklov if you do a release, yes :)

**Comment by dpisklov** [comment]
@NickWard 1.16.136 is there for ya ;p

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
