### ISSUE TITLE
Add StackTrace which is a Throwable explicitly for stack trace recording only.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#75]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.17.1](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.17.1), [BOM-2.17.68](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.68)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.17.1](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.17.1), [BOM-2.17.72](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.72)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.17.1](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.17.1), [BOM-2.17.74](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.74)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
