### ISSUE TITLE
Add support for unique micro second timestamps

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#78]
This is useful for having unique ids which have an embedded timestamp.  This is useful for

- ids which are unique even if a service restarts.
- ids are unique provided that are not created at a sustained rate of 1 million per second.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.17.2](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.17.2), [BOM-2.17.92](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.92)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
