### ISSUE TITLE
Add a multi-threading thread sampler tool.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#79]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.40](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.40), [BOM-2.20.60](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.60)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
