### ISSUE TITLE
Typo in TwoLongValue::getValues

### ISSUE THREAD

**Issue by rogersimmons** [OpenHFT/Chronicle-Core#81]
TwoLongValues::getValues returns a 2-element Long array containing value1 and value2.
Typo causing value2 to be returned in both slots.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.17.4](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.17.4), [BOM-2.17.196](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.196)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.17.4](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.17.4), [BOM-2.17.225](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.225)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.17.4](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.17.4), [BOM-2.17.241](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.241)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
