### ISSUE TITLE
Make the UniqueTimeProvider a class for testing purposes.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#85]
As UniqueTimeProvider is stateful, allow it to be created for testing purposes each time.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.17.14](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.17.14), [BOM-2.17.290](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.290)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
