### ISSUE TITLE
Add support for license checking

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#86]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.17.17](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.17.17), [BOM-2.17.331](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.331)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
