### ISSUE TITLE
StringBuilder/String "coder" field reflection caching

### ISSUE THREAD

**Issue by sheinbergon** [OpenHFT/Chronicle-Core#90]
Currently, for each string (field or value) deserialized using the high-level Chronicle-Queue interface. The `String`/`StringBuilder` `coder` value is assessed using reflection ( to be more precise, the wrong field is assessed, an exception is thrown and then recovered from).

This incurs quite a huge performance penalty for deserialization operation, you might imagine.

I've issued [this](https://github.com/OpenHFT/Chronicle-Core/pull/89) PR to fix this behavior.

**Comment by RobAustin** [comment]
I've merged in the PR so will close this issue, thanks.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.17.27](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.17.27), [BOM-2.17.404](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.404)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.17.27](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.17.27), [BOM-2.17.407](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.407)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
