### ISSUE TITLE
Support Jvm's overriding system.properties

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Core#97]
Added documentation and an example

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.19.2](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.19.2), [BOM-2.19.87](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.87)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.19.2](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.19.2), [BOM-2.19.90](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.90)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Core-2.20.102](https://github.com/OpenHFT/Chronicle-Core/releases/chronicle-core-2.20.102), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
